require("core")
require("config.lazy")

vim.lsp.enable('luals')
vim.lsp.enable('jdtls')
vim.lsp.enable('dartls')
vim.lsp.enable('nil')
vim.lsp.enable('pylyzer')
vim.lsp.enable('rust-analyzer')
vim.lsp.enable('typescript-language-server')
